<?php

namespace AccueilBundle\Repository;

/**
 * PerspectiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerspectiveRepository extends \Doctrine\ORM\EntityRepository
{
}
